config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/temp'

  get 'home/privacy_policy'
  get 'home/faq'
  get 'home/code_of_conduct'
  get 'home/terms_and_conditions'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def privacy_policy
  end

  def faq
  end

  def code_of_conduct
  end

  def terms_and_conditions
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_section_four.html.erb
<section class="section-four">
    <div id="contact" class="row text-center">
		<div class="col-lg-7 col-lg-offset-1 col-md-11 col-sm-11 col-xs-11 section-four-left">
			<h1 id="h1_about_us">about us</h1>
			<div class="text-left">
        <p id="p_about_us">
  				Alfred’s vision is to become the main platform for independent and “live ridesharing”. Alfred will help society to become more efficient and economical with their travel habits within our cities. Alfred will offer a safe social platform for its users to connect with each other and travel together!
  			</p>
			</div>
			<div class="row text-center">
				<div class="col-lg-1 col-md-2 col-sm-2 col-xs-2 div-img-info">
					<div id="img_phone"><%= image_tag("icon_phone.png") %></div>
					<div id="img_email"><%= image_tag("icon_email.png") %></div>
					<div id="img_address"><%= image_tag("icon_address.png") %></div>
				</div>
				<div class="col-lg-7 col-md-10 col-sm-10 col-xs-10 div-info">
					<p id="p_phone">0208 355 13 10</p>
					<p id="p_email">info@alfredridesharing.com</p>
					<p id="p_address">69 Brook St, Myfair, London <br /> W1K 4ER, Great Britain</p>
				</div>
			</div>
		</div>
		<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 text-center section-four-right">
      <div class="row"><h2 id="h2_launch">launching soon on:</h2></div>
      <div class="row div-app-link">
        <div class="col-md-3 col-sm-2 col-xs-2">

        </div>
        <div class="col-lg-12 col-md-3 col-sm-4 col-xs-4" id="icon_appstore">
          <a href="#"><%= image_tag("icon_appstore.png", id: "icon_appstore_link") %></a>
        </div>
  			<div class="col-lg-12 col-md-3 col-sm-4 col-xs-4" id="icon_google">
          <a href="#"><%= image_tag("icon_google.png", id: "icon_google_link") %></a>
        </div>
        <div class="col-md-3 col-sm-2 col-xs-2">

        </div>
      </div>
      <div class="row">
        <h3 id="h3_notify">Want to be notified ?</h3>
        <p id="p_input" style="color: #32aeba;"><%= text_field_tag 'name', nil, {placeholder: 'Your Email', class: "input-placeholder"}%></p>
  			<div id="button_notify_me"><a href=""><%= image_tag("button_notify_me.png", :class => "btn-notify-me") %></a></div>
  			<div class="div-link">
          <a id="a_instagram" href="https://www.instagram.com/Alfredridesharing/?ref=badge"><%= image_tag("icon_insta.png", class: "image_shadow") %></a>
  			  <a id="a_twitter" href="https://twitter.com/AlfredRideShare"><%= image_tag("icon_twitter.png", class: "image_shadow") %></a>
  			  <a id="a_facebook" href="https://www.facebook.com/sharer/sharer.php?u=http%3A//localhost%3A3000/"><%= image_tag("icon_fb.png", class: "image_shadow") %></a>
        </div>
      </div>
		</div>
    <div class="row div-system-link text-center hidden-lg">
      <a href="#"><u>PRIVACY POLICY</u></a>
  		<a href="#"><u>FAQ</u></a>
  		<a href="#"><u>CODE OF CONDUCT</u></a>
  		<a href="#"><u>TERMS AND CONDITIONS</u></a>
    </div>
	</section>

app/views/home/_section_one.html.erb
<section class="row section-one" id="home">
	<div class="col-lg-12 text-center">
    <h1 class="section-title">ALFRED: LET’S COMMUTE TOGETHER</h1>
		<p class="section-content1">
			ALFRED AIMS TO PROVIDE AN ALTERNATIVE FORM OF TRANSPORT FOR
			<br/>
			THE URBAN POPULATION IN THE FORM OF RIDESHARING.
			<br/>
			ALFRED HELPS YOU TO SHARE OR JOIN A RIDE AT THE TAP OF A BUTTON
		</p>
		<div class="content-btn-section1">
			<button type="button" class="btn btn-default btn-find-out-more" id="btn_find_out_more_show" data-toggle="modal" data-target="#myModal">FIND OUT MORE</button>
			<button type="button" class="btn btn-default btn-find-out-more" id="btn_find_out_more_hidden" data-toggle="modal" data-target="#myModal">JOIN ALFRED'S COMMUNITY</button>
		</div>
	</div>
	<!-- Modal -->
	<div id="myModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">
	        	ALFRED - Live Urban Ridesharing
	        </h4>
	      </div>
	      <div class="modal-body">
	        <p style="color: black;">
	        	Alfred was created to solve a well-known problem. In the UK there are over 30 million empty car seats every day. If those seats were occupied, congestion on the road would be reduced as well as CO2 emissions. We would probably not hear of overcrowding in our public transport. Alfred is a solution to our daily commute problems! Alfred is the first cool “live urban ridesharing” mobile app which helps to facilitate its users to ride share and join rides at the tap of a button.
	        </p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">CLOSE</button>
	      </div>
	    </div>
	  </div>
	</div>
</section>

app/views/home/_section_three.html.erb
<section id="ourapp" class="section-three">
	<div class="visible-lg row">
		<div class="col-lg-5 left-section-2">
			<div id="img_driver">
				<%= image_tag("iphone_driver_mode.png", id: "section3_iphone_driver") %>
			</div>
			<div class="section2-pass-text">
				<p>
					Look for a driver on the Alfred map. Simply enter your starting point and destination and request a ride. Alfred will match you with a driver going towards or past your destination .You will just instantly join other users already heading in the same direction. It’s as simple as hitchhiking, cheaper than public transport and fun to meet new friends!
				</p>
			</div>
			<div id="img_message">
				<%= image_tag("iphone_message_board.png", id: "section3_iphone_message") %>
			</div>
		</div>
		<div class="col-lg-2">
			<div id="img_driver_mode"><%= image_tag("icon_driver_mode.png", id: "section3_icon_driver")%></div>
			<div id="img_road_03"><%= image_tag("road_03.png")%></div>
			<div id="img_passenger"><%= image_tag("icon_passenger_mode.png")%></div>
			<div id="img_road_04"><%= image_tag("road_04.png")%></div>
			<div id="img_message_board"><%= image_tag("icon_message_board.png")%></div>
			<div id="img_road_05"><%= image_tag("road_05.png")%></div>
			<div id="img_road_arrow"><%= image_tag("road_arrow.png")%></div>
		</div>
		<div class="col-lg-5 right-section-2">
			<div class="section2-driver-text">
				<p>
					Just simply switch on the driver mode and advertise your journey on the Alfred map. You will become visible to fellow users and you might receive a push up notification from someone who wants to travel with you. Simply advertise the number of seats available in your car, price per seat and your destination. Remember that no profit is allowed and you can only share your costs!
				</p>
			</div>
			<div id="img_passenger_mode">
				<%= image_tag("iphone_passenger_mode.png", id: "section3_iphone_passenger") %>
			</div>
			<div class="section2-message-text">
				<p>
					If you are travelling in the next few days or even the next few hours, why not use the Alfred message board for advertising or requesting journeys such as an airport transfer. Generally this feature is used for booking your journeys in advance.
				</p>
			</div>
		</div>
	</div>
	<div class="hidden-lg section-three-mobile">
		<div class="row text-center div-drive-mode">
			<div class="row">
				<div id="section_three_mobile_arrow_left" class="col-md-5 col-sm-5 col-xs-5 text-right">
					<%= image_tag("mobile/arrow_left.png", :class => "icon-arrow-left")%>
				</div>
				<div id="section_three_mobile_icon_driver" class="col-md-2 col-sm-2 col-xs-2">
					<%= image_tag("mobile/icon_driver.png", :class => "icon_driver")%>
				</div>
				<div id="section_three_mobile_arrow_right" class="col-md-5 col-sm-5 col-xs-5 text-left">
					<%= image_tag("mobile/arrow_right.png", :class => "icon-arrow-right")%>
				</div>
			</div>
		</div>
		<div class="row div-driver-text">
			<div class="col-md-4 col-sm-4 col-xs-4">
				<div id="section_three_mobile_iphone"><%= image_tag("mobile/iphone_driver.png", :class => "img-iphone")%></div>
			</div>
			<div class="col-md-8 col-sm-8 col-xs-8">
				<p id="section_three_mobile_p">
					Just simply switch on the driver mode and advertise your journey on the Alfred map. You will become visible to fellow users and you might receive a push up notification from someone who wants to travel with you. Simply advertise the number of seats available in your car, price per seat and your destination. Remember that no profit is allowed and you can only share your costs!
				</p>
			</div>
		</div>
		<div class="row text-center">
			<div class="section-three-mobile-road3">
				<%= image_tag("mobile/road_03.png", :class => "img-road-03") %>
			</div>
		</div>
	</div>
</section>

app/views/home/_section_two.html.erb
<section class="row text-center section-two" id="services">
	<div class="visible-lg">
		<div class="col-lg-8 col-lg-offset-2">
      <h1 class="section-title2">WHAT IS ALFRED ?</h1>
      <p class="section-content2">
      	Alfred helps you to ride share in our cities in an affordable manner using the concept of car sharing. Alfred is an IOS and Android app which has been developed with the sole purpose of organising and facilitating ridesharing with a few clicks of a button. The app aims to make each task as easy as possible for users as algorithms automatically match users with suitable and relevant rides.
    	</p>
    </div>
    <div class="row">
    	<div id="btn_get_started" class="btn-get-started">
    		<a href="http://www.alfredridesharing.com/competition/"><%= image_tag("button_get_started.png", width: 320)%></a>
    	</div>
    </div>
    <div class="row">
			<div class="col-lg-5 left-section text-left">
				<div class="row">
					<div id="icon_road_traffic" class="col-lg-4">
						<%= image_tag("icon_Road traffic.png", id: "section2_icon_road_traffic")%>
					</div>
					<div class="col-md-8 section-content-text">
						<h2 id="h2_road_traffic">ROAD TRAFFIC</h2>
						<p class="left-section_t1 blog-content">
							London is a great world city but its transport system by the twenty-first century has obviously lagged behind the needs of its economy and its citizens. The population of London has grown slowly over the last 10 years having exceeded 8.5 million in 2015. The financial cost of congestion in London is estimated at £5.5bn a year. UK studies reveals that every day there are 38 million car seats vacant during commuting hours. Alfred aims to fill those empty seats, thus reducing the amount of traffic on our roads.
						</p>
					</div>
				</div>
				<div class="row div_over_crowding">
					<div id="icon_over_crowding" class="col-lg-4">
						<%= image_tag("icon_Over Crowding.png", id: "section2_icon_over_crowding")%>
					</div>
					<div class="col-lg-8 section-content-text">
						<h2 id="h2_over_crowding">Over Crowding</h2>
						<p id="p_over_crowding" class="blog-content">
							It is publically recognised that overcrowding on public transport is unacceptable, and is likely to get worse. The recent introduction of London’s congestion charge has not helped our public transport as travellers routinely find themselves subjected to levels of overcrowding that are not simply uncomfortable, but positively frightening. Alfred offers an alternative means of transport in our cities in the form of ride sharing. Why not commute comfortably with Alfred rather than travel like a sardine in a can!
						</p>
					</div>
				</div>
			</div>
			<div class="col-lg-2">
				<div id="img_road_01"><%= image_tag("road_01.png")%></div>
				<div id="icon_why_alfred"><%= image_tag("icon_why_alfred.png")%></div>
			    <div id="img_road_02"><%= image_tag("road_02.png")%></div>
			</div>
			<div class="col-lg-5 right-section text-left">
				<div class="row">
					<div id="img_increasing_public_transport" class="col-lg-4">
						<%= image_tag("icon_Increasing public transport fares.png", id: "section2_icon_increasing")%>
					</div>
					<div class="col-lg-8 section-content-text">
						<h2 id="h2_increasing_public">Increasing public transport fares</h2>
						<p id="p_increasing_public" class="blog-content">
							Any ideas when this will end? In the UK average rail fare prices have increased by around 80% in a decade and average bus/coach fares have increased by 70%. London's local bus fares have risen by 87% on average since 2002. Alfred helps its users not to increase but decrease their commuting costs by sharing them with others!
						</p>
					</div>
				</div>
				<div class="row right-section-2">
					<div id="img_helping" class="col-lg-4"><%= image_tag("icon_Helping the environment.png", id: "section2_icon_helping")%></div>
					<div class="col-lg-8 content-text">
						<h2 id="h2_helping">Helping the environment</h2>
						<p id="p_helping" class="blog-content">
							Sadly, there is no longer any serious scientific doubt that global climate change is upon us. Continue as we are doing, and the UK transport CO2 emissions are expected to rise by 35% between 1990 and 2030. So it’s critical that we transform our behaviour in order to achieve our emissions reduction targets – and one of the easiest ways we can do this is by making changes to the way we travel. Alfred enables a reduction of cars on the road which in turn significantly reduces CO2 emissions.
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="hidden-lg section-two-mobile">
		<div class="row">
			<h1 class="section-title2">WHAT IS ALFRED ?</h1>
			<p class="section-content2">
				Alfred helps you to ride share in our cities in an affordable manner using the concept of car sharing.
				Alfred is an IOS and Android app which has been developed with the sole purpose of organising and facilitating ridesharing with a few clicks of a button.
				The app aims to make each task as easy as possible for users as algorithms automatically match users with suitable and relevant rides.
			</p>
		</div>
	  <div class="row">
	  	<div id="btn_get_started" class="btn-get-started">
				<a href="http://www.alfredridesharing.com/competition/"><%= image_tag("mobile/button.png", width: 210, :class => "img-get-started")%></a>
			</div>
			<div id="img_road_01_mobile" class="col-md-5 col-sm-5 col-xs-5 col-md-offset-6 col-sm-offset-6 col-xs-offset-6">
				<%= image_tag("mobile/road_01.png", :class => "img_road_01")%>
			</div>
	  </div>
		<div class="row">
		<div id="icon_why_alfred"><%= image_tag("mobile/circle_why_alfred.png", :class => "img-why-alfred")%></div>
		</div>
		<div class="row div-road-traffic">
			<div class="row">
				<div id="section_two_mobile_arrow_left" class="col-md-5 col-sm-5 col-xs-5 text-right">
					<%= image_tag("mobile/arrow_left.png", :class => "img-arrow-left")%>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-2 div-road-traffic-img">
					<%= image_tag("mobile/icon_road_traffic.png", :class => "icon_road_traffic")%>
				</div>
				<div id="section_two_mobile_arrow_right" class="col-md-5 col-sm-5 col-xs-5 text-left">
					<%= image_tag("mobile/arrow_right.png", :class => "img-arrow-right")%>
				</div>
			</div>
			<div class="txt-road-traffic">
				<p id="road_traffic_mobile">London is a great world city but its transport system by the twenty-first century has obviously lagged behind the needs of its economy and its citizens. The population of London has grown slowly over the last 10 years having exceeded 8.5 million in 2015. The financial cost of congestion in London is estimated at £5.5bn a year. UK studies reveals that every day there are 38 million car seats vacant during commuting hours. Alfred aims to fill those empty seats, thus reducing the amount of traffic on our roads.</p>
			</div>
		</div>
		<div class="row">
			<div id="section_two_mobile_road_2"><%= image_tag("mobile/road_02.png", :class => "img-road-02")%></div>
		</div>
	</div>
</section>

app/views/home/code_of_conduct.html.haml
.wrapper{style:"background-color:#32AEBA;color:white;padding-top:150px;"}
  .container
    %h2 Code of Conduct
    %p.MsoNormal{:style => "margin-top:0in;margin-right:0in;margin-bottom:7.5pt;margin-left:141.75pt;text-align:justify;line-height:normal"}
      %b
        %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}  
    %p.MsoNormal{:style => "margin-top:0in;margin-right:0in;margin-bottom:7.5pt;text-align:justify;line-height:normal"}
      %b
        %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
          We only want to know about you!!
    %p.MsoNormal{:style => "margin-bottom:7.5pt;line-height:normal"}
      %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
        When you register with Alfred please only give us genuine information about you. We do not want to know anything about your neighbours!
        Please do not forget that you need to be 18 to use Alfred! By the way, only create one profile per user!
    %p.MsoNormal{:style => "margin-top:0in;margin-right:0in;margin-bottom:7.5pt;text-align:justify;line-height:normal"}
      %b
        %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
          Be sure your watch is on time!
    %p.MsoNormal{:style => "margin-bottom:7.5pt;line-height:normal"}
      %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
        When you book a journey through Alfred, please be sure to be on time!! Someone is waiting for you around the corner!
    %p.MsoNormal{:style => "margin-top:0in;margin-right:0in;margin-bottom:7.5pt;text-align:justify;line-height:normal"}
      %b
        %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
          Good drivers only allowed!
    %p.MsoNormal{:align => "center", :style => "margin-bottom:7.5pt;text-align:center;\r\nline-height:normal"}
      %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
        We want you to follow the rules of the road and take care of your follow passenger and others. We only want to have the best drivers in town! We are not interested to find the new Juan Manuel Fangio! Users are responsible for their own safety. Users are encouraged to carefully read the review and ratings concerning the users they are travelling with.
    %p.MsoNormal{:style => "margin-top:0in;margin-right:0in;margin-bottom:7.5pt;text-align:justify;line-height:normal"}
      %b
        %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
          Good passenger only allowed!
    %p.MsoNormal{:style => "margin-bottom:7.5pt;text-align:justify;line-height:\r\nnormal"}
      %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
        This is not your car! So please behave. Fasten your seat belt and enjoy the ride.
        Respect your Alfred and do not jump on the steering wheels! You are the passenger! Do not put your feet on the dashboard and stay clean and tidy! Smile!
    %p.MsoNormal{:style => "margin-top:0in;margin-right:0in;margin-bottom:7.5pt;text-align:justify;line-height:normal"}
      %b
        %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"} Our principles!
    %p.MsoNormal{:style => "margin-bottom:7.5pt;line-height:normal"}
      %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}
        Alfred is a community of desirable users and nothing else! Alfred is a platform which enables drivers and passengers to meet and travel together toward the same direction.
        Our principles are every simple:
    %p.MsoListParagraphCxSpFirst{:style => "margin-bottom:7.5pt;text-indent:-.25in;\r\nline-height:normal"}
      %ul
        %li Share your culture and way of life, become friends!
        %li Build up new relationships.
        %li Be tolerant and respectful of values, traditions, cultures and religion.
        %li Be open minded and discover new things.
        %li Smile and be kind to your fellow travel companion.

    %p.MsoNormal{:style => "margin-bottom:7.5pt;line-height:normal"}
      %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";"}  
    %p.MsoNormal{:align => "center", :style => "margin-bottom:7.5pt;text-align:center;\r\nline-height:normal"}
      %span{:style => "font-size:11.5pt;font-family:\"Open Sans\";\r\ncolor:black"}  
    %p.MsoNormal
      %span{:lang => "EN"}  
    %p.MsoNormal

:css
  @font-face
   {font-family:Helvetica;
   panose-1:2 11 6 4 2 2 2 2 2 4;}
  @font-face
   {font-family:Wingdings;
   panose-1:5 0 0 0 0 0 0 0 0 0;}
  @font-face
   {font-family:"Cambria Math";
   panose-1:2 4 5 3 5 4 6 3 2 4;}
  @font-face
   {font-family:Calibri;
   panose-1:2 15 5 2 2 2 4 3 2 4;}
  @font-face
   {font-family:Tahoma;
   panose-1:2 11 6 4 3 5 4 4 2 4;}
  @font-face
   {font-family:"Open Sans";}
  /* Style Definitions */
  p.MsoNormal, li.MsoNormal, div.MsoNormal
   {margin-top:0in;
   margin-right:0in;
   margin-bottom:10.0pt;
   margin-left:0in;
   line-height:115%;
   font-size:11.0pt;
   font-family:"Calibri","sans-serif";}
  p
   {margin:0in;
   margin-bottom:.0001pt;
   font-size:12.0pt;
   font-family:"Times New Roman","serif";}
  p.MsoAcetate, li.MsoAcetate, div.MsoAcetate
   {mso-style-link:"Balloon Text Char";
   margin:0in;
   margin-bottom:.0001pt;
   font-size:8.0pt;
   font-family:"Tahoma","sans-serif";}
  p.MsoListParagraph, li.MsoListParagraph, div.MsoListParagraph
   {margin-top:0in;
   margin-right:0in;
   margin-bottom:10.0pt;
   margin-left:.5in;
   line-height:115%;
   font-size:11.0pt;
   font-family:"Calibri","sans-serif";}
  p.MsoListParagraphCxSpFirst, li.MsoListParagraphCxSpFirst, div.MsoListParagraphCxSpFirst
   {margin-top:0in;
   margin-right:0in;
   margin-bottom:0in;
   margin-left:.5in;
   margin-bottom:.0001pt;
   line-height:115%;
   font-size:11.0pt;
   font-family:"Calibri","sans-serif";}
  p.MsoListParagraphCxSpMiddle, li.MsoListParagraphCxSpMiddle, div.MsoListParagraphCxSpMiddle
   {margin-top:0in;
   margin-right:0in;
   margin-bottom:0in;
   margin-left:.5in;
   margin-bottom:.0001pt;
   line-height:115%;
   font-size:11.0pt;
   font-family:"Calibri","sans-serif";}
  p.MsoListParagraphCxSpLast, li.MsoListParagraphCxSpLast, div.MsoListParagraphCxSpLast
   {margin-top:0in;
   margin-right:0in;
   margin-bottom:10.0pt;
   margin-left:.5in;
   line-height:115%;
   font-size:11.0pt;
   font-family:"Calibri","sans-serif";}
  span.BalloonTextChar
   {mso-style-name:"Balloon Text Char";
   mso-style-link:"Balloon Text";
   font-family:"Tahoma","sans-serif";}
  .MsoChpDefault
   {font-family:"Calibri","sans-serif";}
  .MsoPapDefault
   {margin-bottom:10.0pt;
   line-height:115%;}
  @page WordSection1
   {size:595.3pt 841.9pt;
   margin:1.0in 1.0in 1.0in 1.0in;}
  div.WordSection1
   {page:WordSection1;}
  /* List Definitions */
  ol
   {margin-bottom:0in;}
  ul
   {margin-bottom:0in;}

app/views/home/index.html.erb
<div class="section-container">
	<%= render "section_one" %>
	<%= render "section_two" %>
	<%= render "section_three" %>
	<%= render "section_four" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alfred</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body data-spy="scroll" data-target=".navbar" data-offset="50">
  	<%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="row footer text-center">
  <div class="col-lg-5">
    <p>ALFRED RIDESHAIRING LTD | COPYRIGHT © 2016</p>
  </div>
  <div class="col-lg-7 visible-lg text-right">
  		<a href="<%= home_privacy_policy_path %>">PRIVACY POLICY</a>
  		<a href="<%= home_faq_path %>">FAQ</a>
  		<a href="<%= home_code_of_conduct_path %>">CODE OF CONDUCT</a>
  		<a href="<%= home_terms_and_conditions_path %>">TERMS AND CONDITIONS</a>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav id="header" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    </div>
    <div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#home">HOME</a></li>
          <li><a href="#services">SERVICES</a></li>
          <li class="nav-logo">
              <div class="nav-triangle"></div>
              <a id="icon_logo" href="http://alfredridesharing.com/"><%= image_tag("logo.png", id: "img_logo")%></a>
          </li>
          <li><a href="#ourapp">OUR APP</a></li>
          <li><a href="#contact">CONTACT</a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>